@startuml
header
Bowling Game
endheader

object Game {
	+Roll(pins int)
	+Score() int
}

note top of Game
	The requirement
end note

object Frame {
	+Score() int
}

Game --> Frame:10

object Roll {
	-Pins int
}

Frame --> Roll:1..2

Frame --> Frame:nextframe

note right of Frame
	Frame score for spares and 
	strikes uses the next frame
end note

object FrameTenth {
	+Score() int
}

FrameTenth --|> Frame
FrameTenth --> Roll:1..3

@enduml
